name: Publish to Docker Hub

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the image
        run: docker build -t sig-tomcat .
