name: Publish to Docker Hub

on:
  workflow_dispatch:

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Compute which base tags to build
        id: set-matrix
        run: echo "::set-output name=matrix::$(bash build/get_base_tags.sh)"
    
  build:
    needs: prep
    runs-on: ubuntu-latest
    strategy:
      matrix:
        baseTag: ${{ fromJson(needs.prep.outputs.matrix) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Get short commit hash
        id: shortSha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
      - name: Update Dockerfile
        run: sed -ie 's/^FROM .*/FROM tomcat:${{ matrix.baseTag }}/g' Dockerfile
        
      - name: Check Dockerfile
        run: grep FROM Dockerfile
      
      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            sigcorp/tomcat:${{ matrix.baseTag }}
            sigcorp/tomcat:${{ matrix.baseTag }}-${{ steps.shortSha.outputs.sha_short }}
            sigcorp/tomcat:${{ matrix.baseTag }}-${{ github.run_number }}
