name: Publish to Docker Hub

on:
  workflow_dispatch:
    inputs:
      baseTag:
        description: tomcat tag for the FROM directive in the Dockerfile
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Get short commit hash
        id: shortSha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
      - name: Update Dockerfile
        run: sed -ie 's/^FROM .*/FROM tomcat:${{ github.event.inputs.baseTag }}/g' Dockerfile
        
      - name: Check Dockerfile
        run: grep FROM Dockerfile
      
      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            sigcorp/tomcat:${{ github.event.inputs.baseTag }}
            sigcorp/tomcat:${{ github.event.inputs.baseTag }}-${{ steps.shortSha.outputs.sha_short }}
            sigcorp/tomcat:${{ github.event.inputs.baseTag }}-${{ env.GITHUB_RUN_NUMBER }}
